/**
 * eduflex.js
 * Logs into Eduflex and scrapes the DocentRooster for the coming 2 weeks.
 * Returns an array of appointment objects.
 */

const puppeteer = require('puppeteer');

const EDUFLEX_URL   = 'https://web.eduflexcloud.nl/JA/webma/Pages/Default';
const ROOSTER_URL   = 'https://web.eduflexcloud.nl/JA/webma/Pages/DocentRooster';

async function getEduflexRooster() {
  const username = process.env.EDUFLEX_USER;
  const password = process.env.EDUFLEX_PASS;

  if (!username || !password) {
    throw new Error('EDUFLEX_USER and EDUFLEX_PASS environment variables are required');
  }

  console.log('🔑 Eduflex: inloggen...');

  const browser = await puppeteer.launch({
    headless: 'new',
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',  // Required for GitHub Actions
      '--disable-gpu',
    ],
  });

  try {
    const page = await browser.newPage();
    await page.setViewport({ width: 1280, height: 900 });

    // ── Step 1: Load login page ──────────────────────────────────────────────
    await page.goto(EDUFLEX_URL, { waitUntil: 'networkidle2', timeout: 30000 });

    // Find the username/password fields — Eduflex uses ASP.NET so field IDs
    // may contain long autogenerated names; we search by input type as fallback.
    const usernameSelector = 'input[name*="gebruiker"], input[id*="gebruiker"], input[type="text"]:first-of-type';
    const passwordSelector = 'input[name*="wachtwoord"], input[id*="wachtwoord"], input[type="password"]';

    await page.waitForSelector(passwordSelector, { timeout: 10000 });
    await page.type(usernameSelector, username, { delay: 50 });
    await page.type(passwordSelector, password, { delay: 50 });

    // Submit the login form
    await Promise.all([
      page.waitForNavigation({ waitUntil: 'networkidle2', timeout: 30000 }),
      page.click('input[type="submit"], button[type="submit"]'),
    ]);

    console.log('✅ Eduflex: ingelogd');

    // ── Step 2: Navigate to DocentRooster ────────────────────────────────────
    await page.goto(ROOSTER_URL, { waitUntil: 'networkidle2', timeout: 30000 });

    // Collect roster for THIS week and NEXT week
    const alleItems = [];

    for (let weekOffset = 0; weekOffset <= 1; weekOffset++) {
      if (weekOffset > 0) {
        // Click "volgende week" button
        const volgendeWeekSelector = 'a[id*="volgende"], a[title*="olgende"], input[value*="olgende"]';
        try {
          await Promise.all([
            page.waitForNavigation({ waitUntil: 'networkidle2', timeout: 20000 }),
            page.click(volgendeWeekSelector),
          ]);
        } catch (e) {
          console.warn('⚠️  Kon niet naar volgende week navigeren:', e.message);
          break;
        }
      }

      // ── Step 3: Parse the roster table from the page ──────────────────────
      const weekItems = await page.evaluate(() => {
        const items = [];

        // Eduflex renders a week-grid; each cell typically has class "rooster-item",
        // "afspraak", or similar. We cast a wide net and filter empty cells.
        const cells = document.querySelectorAll(
          '.rooster-item, .afspraak, td.les, [class*="les"], [class*="afspraak"], [class*="rooster"]'
        );

        cells.forEach(cell => {
          // Try to extract text fields from child elements or fall back to innerText
          const getText = (selectors) => {
            for (const sel of selectors) {
              const el = cell.querySelector(sel);
              if (el && el.innerText.trim()) return el.innerText.trim();
            }
            return null;
          };

          const vak    = getText(['.vak', '.subject', '.vakcode', '[class*="vak"]', '[class*="subject"]']);
          const tijd   = getText(['.tijd', '.time', '.uur', '[class*="tijd"]', '[class*="time"]']);
          const lokaal = getText(['.lokaal', '.room', '.zaal', '[class*="lokaal"]', '[class*="room"]']);
          const groep  = getText(['.groep', '.klas', '.group', '[class*="groep"]', '[class*="klas"]']);
          const datum  = getText(['.datum', '.date', '[class*="datum"]', '[class*="date"]']);

          // Also try reading from data attributes (some ASP.NET grids use these)
          const dataVak   = cell.dataset.vak   || cell.dataset.subject || null;
          const dataTijd  = cell.dataset.tijd  || cell.dataset.time    || null;
          const dataStart = cell.dataset.start || cell.dataset.begin   || null;
          const dataEind  = cell.dataset.eind  || cell.dataset.end     || null;
          const dataLokaal= cell.dataset.lokaal|| cell.dataset.room    || null;

          const item = {
            vak:    vak    || dataVak    || null,
            tijd:   tijd   || dataTijd   || (dataStart && dataEind ? `${dataStart} - ${dataEind}` : null),
            lokaal: lokaal || dataLokaal || null,
            groep:  groep  || null,
            datum:  datum  || null,
            bron:   'eduflex',
            // Keep raw text as fallback for debugging
            _raw:   cell.innerText.trim().slice(0, 200),
          };

          // Only include cells that have at least some content
          if (item.vak || item.tijd || (item._raw && item._raw.length > 3)) {
            items.push(item);
          }
        });

        // Deduplicate by raw text
        const seen = new Set();
        return items.filter(i => {
          if (seen.has(i._raw)) return false;
          seen.add(i._raw);
          return true;
        });
      });

      console.log(`   Week +${weekOffset}: ${weekItems.length} items gevonden`);
      alleItems.push(...weekItems);
    }

    console.log(`✅ Eduflex totaal: ${alleItems.length} afspraken`);
    return alleItems;

  } finally {
    await browser.close();
  }
}

// Allow running standalone for testing: node scripts/eduflex.js
if (require.main === module) {
  getEduflexRooster()
    .then(data => console.log(JSON.stringify(data, null, 2)))
    .catch(err => { console.error(err); process.exit(1); });
}

module.exports = { getEduflexRooster };
